### ISSUE TITLE
Ordering Windows by most recently used

### ISSUE THREAD

**Issue by a-pirard** [ericpromislow/tabhunter#123]
Extremely well done Tabhunter, congratulations !!!
When I restart Firefox, the most recently used windows appear open on top of the foreground.
Would there be inside Firefox a windows ordering by most recently used?
Impossible to say for other restarted windows as they only appear alphabetically.
If it exists, hat would be a very nice way to order the Windows/Tab list.
TIA; Cheers.

**Comment by ericpromislow** [comment]
I think Tabhunter does what you want. Have you pressed the "↓ More …" button and then selected the "Window/Tab" option from the "Sort By…" section?

I actually haven't tried to figure out where the window numbers come from, but I wouldn't be surprised if they're by recentness. 

And because of the nice words, there's a poorly documented search syntax.

`{w:3}` will show only tabs from window #3

`{w:1:10-20}` will show only tabs 10 through 20 from window #1.

`{w:1:10-20}cats` will show only matches from tabs 10 through 20, window #1, tahat have the word `cats` in the URL and/or the title.

Please close this issue if this is what you're looking for.

**Comment by a-pirard** [comment]
On 10/01/24 23:19, Eric Promislow
      wrote:
    
    
      
      I think Tabhunter does what you want. Have you
        pressed the "↓ More …" button and then selected the "Window/Tab"
        option from the "Sort By…" section?
      I actually haven't tried to figure out where the
        window numbers come from, but I wouldn't be surprised if they're
        by recentness.
    
    You're right, Eric.
    I'm using "Window/Tab" already and if H is the highest window number
    and if I open two new windows 1 and 2, they get numbers H+1 and H+2.
    Now if I close window 1, window 2 gets number H+1.
    The most recent windows have the highest numbers.
    I should have noticed myself, but I thought the windows were keeping
    their numbers ;-)
    
      And because of the nice words, there's a poorly
        documented search syntax.
      {w:3} will show
        only tabs from window #3
      {w:1:10-20} will
        show only tabs 10 through 20 from window #1.
      {w:1:10-20}cats
        will show only matches from tabs 10 through 20, window #1, tahat have the word cats in the URL and/or the title.
      Please close this issue if this is what you're
        looking for.
    
    Yes I close it.
    
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ericpromislow/tabhunter/issues/123#issuecomment-1885833536",
"url": "https://github.com/ericpromislow/tabhunter/issues/123#issuecomment-1885833536",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by a-pirard** [comment]
Many thanks !!!
