### ISSUE TITLE
[Feature request] accept list of urls to delete

### ISSUE THREAD

**Issue by rieje** [ericpromislow/tabhunter#138]
I've been searching far and wide for an extension that accepts a list of urls to delete their tabs. Very few even delete tabs passed as urls.

The problem is the this large list of urls are already tabs I want deleted and they don't share any regex pattern, so it would be a long manual process to delete these tabs one at a time. Accepting list of urls to delete would be make my particular workflow possible (I always have list of tabs to delete since I just multiple profiles and across different machines and devices).

**Comment by dnwe** [comment]
@rieje whilst a valid usecase, bulk closing of tabs based on a list of fixed URLs rather than a query pattern seems like something that is best suited to a commandline/script input into Firefox/Chrome rather than necessarily in tabhunter's UI-based approach

Have you seen [brotab](https://github.com/balta2ar/brotab/) which seems well-suited to your task? A combination of `bt list | grep -f your-urls.txt | cut -d'\t' -f1 | xargs --no-run-if-empty bt close` seems like it would do what you wanted

**Comment by ericpromislow** [comment]
It's easy to export all your loaded tabs with tabhunter -- just select all the tabs with no filter, copy by URL, and paste into an editor.  But because tabhunter doesn't (currently) have access to the local filesystem, there's no ready way to read in the list of tabs. So I'd install brotab and give that a shot.
