### ISSUE TITLE
Severe performance problems with 1.0.20 to 1.0.23 or 24 (?)

### ISSUE THREAD

**Issue by reikred** [ericpromislow/tabhunter#65]
I'm a power-user that has 100s if not a 1000 tabs open routinely. Right now as I am typing this I have in fact 1250 tabs open on this very browser. As you can imagine, Tabhunter is an absolute lifesaver when dealing with so may windows and tabs.

In the last several days I have noticed severe performance problems with my firefox (42.0/linux-x86_64) browser. The browser was constantly running at 100+ % CPU (100+ because multicore), and for minutes at a time there was no response when trying to do anything at all. With all extensions off (--safe-mode option), there was no problem.

I did some profiling, and one of the the items that stood out was  asyncTabCollector.js, which I noticed belongs to Tabhunter, and that also has been modified in some of the aforementioned recent  versions.

So: Can developer please confirm or deny that there has been a performance problem associated with the recent changes? It looks like things are better now, with 1.0.24, but it would be nice to now what is going on. I took me hours upon hours to find out how to profile, and to eliminate other extensions, and I may still have gotten the attribution wrong. But any information you may have on this topic would be helpful.

**Comment by morspin** [comment]
No, I think you're right.  You might not be aware that with the
multi-process changes about to land in Firefox Tabhunter was reported to
cause firefox to run at 100% CPU.  I've updated it so it no longer uses the
high-CPU "CPOW" proxy, but I can see that it would still be hogging CPU.
I'm going to try a fix to make it less of a CPU hog.

**Comment by reikred** [comment]
Hi Morspin, thank you very much for replying. Is part of the problem perhaps also that Tabhunter frequently searches through a window list to look for "new windows". That also appears to be a new/recent feature that might use a lot of CPU.

I had also an idea: Wouldn't be nice if all extensions had a "pause" button in the settings, so that one could more easily debug whether it is using a lot pf cpu/resources. This would be different than a disable/enable, perhaps, since the latter type often requires a restart. Thanks much, and please keep us posted.

**Comment by morspin** [comment]
Well, what's happening is there's a lot more activity going on. For every
tab you have loaded, there's a message from the top-level to the tab, and
another going back. The next update will do things a little differently --
rather than send off messages to all the tabs in one barrage, Tabhunter
will talk to one tab at a time, and will then do the next update in a
setTimeout so control is handed back to any other part of Firefox that
wants to do something. I've noticed with 100 tabs it takes longer to update
the list, but that's currently with a lot of debug output to the console.

As for your question, Tabhunter should only traverse the windows on an
update event. Currently it does traverse all the windows even when the
event happens in only one window. I definitely welcome a pull request with
an optimization that just updates the tabs in the window that changed.

**Comment by reikred** [comment]
I'm not in a position to hack javascript, unfortunately. My knowledge of javascript is at the kindergarten level, and firefox API knowledge even worse. I only managed to profile the execution because I was used to cc -pg and gprof in the old days :). And I was desperate on top of that. So I may given the impression of being more sophisticated than I really am :-).

Just speculating, could a tab created/destroyed/URL-has-changed event be set up to create a callback to Tabhunter? That might be faster than querying each tab with messages down/up. But you probably thought of that already, or maybe it is not possible.

Great idea with the setTimeout, that will help in any case.

**Comment by morspin** [comment]
Good guess on the architecture -- tabhunter responds to the exact events
you've listed (+ DOMContentChanged to handle the case where a newly opened
tab finally connects to its target). I'm thinking of a way to update the
list incrementally -- the hardest part is that
DOMContentChanged event, because I don't know *which* tab changed,  so I
have to check all of them.

You're lucky I'm doing this work on a 10-year-old laptop. I can't run 1000
tabs -- 200 is more enough to bring Tabhunter to its knees. So when I solve
this problem, it should be readily obvious.

**Comment by reikred** [comment]
I think it is indeed a good software engineering practice to develop on older machines. It makes performance issues so much more obvious :).

How do you feel about the idea of extensions having a "pause" button in general? I mean, there has to be "checkpoints" sprinkled around the code where the pause flag is checked and acted upon. Also, there has to be a way to see the status of being paused. Right now I have 16 extensions running, and it is not easy to figure out which one is the culprit when one of them goes a bit rogue, and it happens quite regularly!!

**Comment by morspin** [comment]
The pausing could easily be done with a pref.  I'd accept a pull request,
but don't have time to do it myself.

**Comment by reikred** [comment]
I totally understand. I'll be looking forward to seeing your other developments. Thanks a bunch.

**Comment by ericpromislow** [comment]
Should be fixed by version 1.0.27.  Changes include unwinding two loops, one to use a setTimeout after each iteration, the other loop replaced by a worker queue. There are still other areas where loops are used, and I can see that for a large enough # of tabs, loops should be considered harmful (to performance).

**Comment by ericpromislow** [comment]
@reikred You can easily go back to 1.0.22 from here: https://addons.mozilla.org/en-US/firefox/addon/tabhunter/versions/  If you do, please stay tuned for updates. You're exercising this add-on more than anyone else, and I'm happy to ensure the add-on can scale up to that level. We're still talking < 100,000 items -- in the computer world 1450 shouldn't be a daunting number. Most likely my change \#3 in the 1.0.27 drop is causing the perf hit.

**Comment by reikred** [comment]
Hi Eric, I just updated from 1.0.24 to 1.0.27 -- I will report back in a day or two how it is going. Thank you for your attention to this matter.

**Comment by morspin** [comment]
I added metrics to see where the bottlenecks are. I was right about that
initial loop -- there's no need for Tabhunter to walk the list of windows
and
tabs using setTimeout in order to avoid hogging the CPU -- I can process
80 tabs in 1 msec on a slow machine, so I figure 1400 can be done in less
than 50 msec (yes, I know, it's not standard multiplication -- I'm storing
the data as I go). With the non-iterative approach it was more like 500 msec
for 80 tabs -- maybe 30 seconds for 1400.  Yes, that's crazy.

Message-passing takes about 5 msec per tab on my slow laptop. If
it's 2 msec on your faster one (and I assume you're using a newer
machine if you can run that many tabs, 1450 * 2 => 2.9 seconds.

I'm about to put v1.0.29 up. Looking forward to your report.


- Eric

**Comment by reikred** [comment]
I can report good performance with 1.0.27 so far, but it has been only 3 hrs :). CPU load looks lower, possibly also memory usage, responsiveness is better.

 I'm going to be away from my desktop quite a bit for the next 2-3 days, so may not be able to report back immediately. Sorry about that, will try when I can.

**Comment by morspin** [comment]
1.0.29 should be noticeably better.

**Comment by reikred** [comment]
I like the new status message on the bottom,

"Matched n1/n2 tabs, n3 still to ptocess"

I can see it still takes several seconds  to search 1843 tabs, but when NOT searching, there appears to be less CPU usage, which is great. Looking forward to testing 1.0.29 later.

**Comment by reikred** [comment]
A performance report, and a question: With Tabhunter 1.0.29, starting a search took about 3 seconds for 1974 tabs to appear in the Tabhunter window. That is a big improvement from 1.0.24 and perhaps also from 1.0.27. Very nice.

Question: I'm experiencing very long startup (and shutdown) times with firefox. It has been like that for many months. I am of course using the "Don't load tabs until selected" setting. What I am wondering about is whether Tabhunter gets intensely involved during the startup or shutdown of firefox, as for example might happen if it gets a callback/message whenever a window or a tab is created or destroyed. Please note, by "startup time" I mean the time elapsed from starting firefox until the active tab has been fully presented (rendered) in each window, and also that the title of the window appears on the icon.

**Comment by morspin** [comment]
I would recommend not opening Tabhunter until you've loaded all your
windows.  And, since Tabhunter does track every tab-close, albeit after a
1-second delay, I would recommend closing it before shutting down Firefox.
Although I must express surprise that you aren't running long-running
Firefox sessions -- I run it for days, unless and until its using so much
memory it needs to be restarted.

Running that many tabs *is* excessive. Maybe you need a dedicated
application. You could always contact me privately, in confidence,
to let me know your thoughts on that. A bunch of my former colleagues work
down the street from me at a Mozilla office, and they're surprised
when I tell them about Tabhunter people who have 500 tabs up. 1450 was an
outlier. 1974 is off the charts. Is your close box broken? :)

Respectfully,
Eric
