### ISSUE TITLE
Blank window in PaleMoon

### ISSUE THREAD

**Issue by DrkShadow** [ericpromislow/tabhunter#66]
In PaleMoon (latest), Tabhunter now shows an empty, gray window with the Close and Go buttons beginning at version 1.0.22. This is still true at 1.0.29.

The issue may be related to the overlay UUID, 8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4. I'm unsure.

**Comment by ericpromislow** [comment]
The DOM Inspector on PaleMoon shows different results from the inspector on Firefox. With FF, I see the outer xul:vbox contains 4 scripts and 4 elements I specified, including vbox#th.1 . On PaleMoon, it shows only the 4 scripts.  This looks like a bug in PaleMoon. I added an entry for PaleMoon in the install.rdf file with that UUID, but saw the same results with the same underlying missing elements in the DOM Inspector. I filed a bug at PaleMoon. The forum is manually moderated, don't know when the report will appear.

Did Tabhunter ever work on PaleMoon? Anyway, it's their issue, not mine.

**Comment by DrkShadow** [comment]
TabHunter works until version 1.0.20. With 1.0.22 and later, the empty window appears.

**Comment by DrkShadow** [comment]
TabHunter works until version 1.0.20. With 1.0.22 and later, the empty window appears.

**Comment by ericpromislow** [comment]
It might be the chrome.manifest - due to changes in Firefox I had to stop  jarring the extension.

But I have to face facts -- you're the only person I know using PaleMoon - I had never heard of
it until today. I don't have time to figure out why we're seeing this breakage, regardless of whether the fault is on the Tabhunter side or the PaleMoon side.  You can stick with an older version of Tabhunter - you can find them at https://addons.mozilla.org/en-US/firefox/addon/tabhunter/versions/ . All the work I've done since 1.0.5 is to support multi-process Firefox. I hadn't made a checkin for something like 4 years before that. I have a feeling PaleMoon isn't going to go multi-process, so you're not losing out on anything by staying with an older version.

Thanks for the bug report though. I always appreciate them, even if I just chuck them over the wall.

**Comment by Lister0fSmeg** [comment]
I can confirm that v1.0.20 is the last version that partially works on Palemoon. However you need to go back to 1.0.5.1 to get full functionality where previous search terms are retained on subsequent opening of TH.
