### ISSUE TITLE
Bookmark reload rearrange

### ISSUE THREAD

**Issue by rayman89** [ericpromislow/tabhunter#72]
First of All I wanna say I really like your addon. Thanks for creating it.

I was wondering if it would be possible to add two buttons one to bookmark and another to reload the selected tabs. And it would be great (idk if WE supports it yet) to be able to drag the selected tabs to put them in a different place in the tab list and that this change re arranges the tabs for real and/or if you could add a button that groups the selected tabs so for example lets say I have open 10 tabs of youtube but between those tabs there are other tabs then when selecting all the youtube tabs and pressing the "group tabs" button  it will put them all side by side.

**Comment by ericpromislow** [comment]
So using the existing UI, I see two new features:

1. Select a bunch of tabs. Right-click something (and I have to admit I haven't figured out a nice way to do context menus in the WebExtensions world, but that's mainly because I'm one of those people who is more conversant with XUL than HTML. Now that XUL is dead that will change eventually...) to indicate you want to move the tabs to an existing window, or a new one.  Yes, that's easy with WE.

2. Select a bunch of tabs.  Press the Bookmark... button. You get a new UI thing, where you can either choose an existing bookmark container or create a new one.  It's possible. More likely that I would accept a PR rather than do it myself. And now that the add-on is in HTML rather than XUL, there are about 1,000,000 x more people that can contribute.

3. Reloading existing tabs.... This sounds like something to be done with a bookmark manager rather than Tabhunter, as Tabhunter is concerned only with loaded tabs. I'll have to think about this.

Glad you like it. Would you mind going to https://chrome.google.com/webstore/search/tabhunter?hl=en-GB , installing the "Tabhunter" add-on without the space (the one that's at 2.0, not 0.1), and giving it a good rating? Now that it's finally in the Chrome store, I'm hoping it gets discovered.

**Comment by rayman89** [comment]
Why reloading selected open tabs using the open tab list in tabhunter would have something to do with a bookmark manager?

Maybe I explained myself wrong but all the suggestions had to do with open tabs that are on the list of open tabs in tabhunter.

The only thing that I asked regarding bookmarks was to be able to select from the tabhunter tab list for example tabs 2 4 6 and by clicking a button or something all those tabs would be saved to a bookmark folder or some place you choose.

With re arranging tabs I mean if you have tabs 1 2 3 4 5 6 7 8 being able to select 2 3 4 and moving them to something like  1 5 6 2 3 4 7 8 and the group tabs would be like selecting 2 4 6 and would put them like  1 2 4 6 3 5 7 8 or 1 3 2 4 6 5 7 8 or 1 3 5 2 4 6 7 8 depending on which of the 2 4 5 tabs you had the focus on.



>Glad you like it. Would you mind going to https://chrome.google.com/webstore/search/tabhunter?hl=en-GB , installing the "Tabhunter" add-on without the space (the one that's at 2.0, not 0.1), and giving it a good rating? Now that it's finally in the Chrome store, I'm hoping it gets discovered.

I'll gladly do it.

**Comment by ericpromislow** [comment]
> The only thing that I asked regarding bookmarks was to be able to select from the tabhunter tab list for example tabs 2 4 6 and by clicking a button or something all those tabs would be saved to a bookmark folder or some place you choose.

Yes, this is what I had in mind.

> With re arranging tabs I mean if you have tabs 1 2 3 4 5 6 7 8 being able to select 2 3 4 and moving them to something like 1 5 6 2 3 4 7 8 and the group tabs would be like selecting 2 4 6 and would put them like 1 2 4 6 3 5 7 8 or 1 3 2 4 6 5 7 8 or 1 3 5 2 4 6 7 8 depending on which of the 2 4 5 tabs you had the focus on.

So I think here's the Simplest Thing That Would Work: Like you say, the current tab is tab 5 (let's say in Window A).  You select tabs (2 4 6) in windows (A B B) respectively. This would then pull those tabs out of their current locations and move them to the right of tab 5 in Window A.  Sounds easy. No need for a new extension

**Comment by rayman89** [comment]
I was talking about grouping tabs that are in the same window so if they are separeted by tabs in between they would get one next to the other but being also able to do so across windows would be useful too.

**Comment by ericpromislow** [comment]
Bookmarking groups of tabs is now in 2.1.5 -- I'm going to close this issue. If you want some of the other features you mentioned done, please open each one in a separate issue.
