### ISSUE TITLE
Ability to resize and reposition window

### ISSUE THREAD

**Issue by toad01** [ericpromislow/tabhunter#76]
New version (2.0.1) is virtually instantaneous listing all tabs! and the new audio only selection is very useful. Many thanks.

I do find the window rather small as only 10 tabs are listed at a time and I use tabhunter for culling unwanted tabs. Would it be possible to either increase the size or allow resizing and also repositioning of the window?

**Comment by OregonGhost** [comment]
I second this. I previously had TabHunter always open in full screen, because not only am I using it for quickly finding a single window, I also use it for closing large groups of tabs. I'd be fine with a full-screen (or rather, a full-firefox-window) option, but I need to display way more lines and I like the lines to be visible entirely, not that tiny small box that is currently displayed. Otherwise, this will make TabHunter mostly useless for me (in addition to the keyboard shortcut not working at all now, but luckily you're already working on that).

**Comment by equalsJeffH** [comment]
I third @toad01's comments.  Perhaps having some preference settings where one can indicate whether they want the small fixed pop-up dialog window (as in 2.0.1), or the prior full separate window (tho I like the change having the action buttons visible in the window border, but would be nice if the context menu still existed).  I've used Tabhunter for ages and rely on it heavily. thanks!

**Comment by ericpromislow** [comment]
For the time being, small popup windows are gone. Maybe it would be possible to create a new window with an html page hosting the tabhunter table, but I'm not sure how much work that will be. Once again, contributions are welcome.  As for the context menu, getting it to work with the new API turned out to take more CSS skills than I had at the moment. Maybe one day I'll take the time to build something, but for now I'm sticking with the buttons. Of course, as I said somewhere before, contributions are welcome.

**Comment by ericpromislow** [comment]
Sorry, this isn't going to happen with the current WebExtensions API, at least by me.

**Comment by r-a-y** [comment]
I know this is an older issue, but for those that want to open TabHunter in a full tab, here's the URL for the popup:

`moz-extension://da2ae89b-adca-4055-983c-d2109c70782e/popup/tabhunter.html`

You'll still need to manipulate the CSS so the contents will expand the full-size. You can find some sample CSS to customize this page here: https://github.com/ericpromislow/tabhunter/issues/114#issuecomment-855015180

That CSS is meant for the popup, so you'll have to tweak the CSS to your liking.
