### ISSUE TITLE
Re arrange tabs

### ISSUE THREAD

**Issue by rayman89** [ericpromislow/tabhunter#82]
Could you implement a way to drag and drop tabs (one or many) from the tabhunter list of tabs to change their order?

**Comment by ericpromislow** [comment]
Done in version 2.2.2 -- Only implemented when viewing tabs by Window/Tab position. It didn't feel right with the other tabs when you didn't have the tabs being moved around, as the tabhunter view never changed and didn't give any feedback. But lots of things happen with Window/Tab position.

**Comment by reikred** [comment]
Hi Eric, this feature is very useful , but it is missing something essential: Move all selected tabs so that they are next to (after) another tab, think of it as the destination tab.  Here are some uses cases to explain better what I mean: (a) move all the selected tabs so that they are placed after the CURRENT tab in the CURRENT window  (b) move all the selected  tabs so that they are next to (after) the topmost tab in the TabHunter list.

(a)  is just a missing functionality (b) is sort of implemented already, but it does not work  because there is no position to drag the list to underneath the topmost item, because "the list is already there", so no tabs actually move. More generally,. maybe (b) could be implemented with more flexibility by (a1) selecting the destination separately (color it in the list) or (a2) make the destination tab be the first UNselected tab in the tabhunter list or (a3) some other scheme for selecting the destination.

Maybe I will create a new request for this, since I can't reopen?
