### ISSUE TITLE
Suspend/Discard tab(s)

### ISSUE THREAD

**Issue by rayman89** [ericpromislow/tabhunter#85]
Could you add the functionality to suspend/discard selected tabs please?

**Comment by ericpromislow** [comment]
The "Close tab" button closes tabs. Is this what you mean?

**Comment by rayman89** [comment]
No. Discard tabs https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/discard

**Comment by ericpromislow** [comment]
oh ok.

**Comment by equalsJeffH** [comment]
since AFAICT Firefox auto-discards tabs according to some criteria (?) [1] , perhaps a sorting (or hunting?) option (see #77) for "non-discarded tabs" might be useful?  otherwise one cannot really tell which are presently "active" and which are "discarded" (?)

[1] there used to be an extension for this "bartab" (?), the dvlpr got hired by Moz, and the functionality incorp'd in FF (AFAIK).

**Comment by ericpromislow** [comment]
Done in 2.1.9
